name: Build extension
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g aha-cli
      - run: yarn install
      - run: "yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version"
      - run: aha extension:build
      - uses: EndBug/add-and-commit@v9
        with:
          message: "v${{ github.event.inputs.version }}"
          add: "package.json"
      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.version }}"
          title: "${{ github.event.inputs.version }}"
          files: |
            *.gz